version: "3"

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=vaalikoppi
      - POSTGRES_USER=vaalikoppi

  vaalikoppi:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 80:80
    environment:
      - DATABASE_URL=postgres://vaalikoppi:secret@db:5432/vaalikoppi
      - HMAC_KEY=cd7baa16ea412b9a210aa315a590a57545863c1089d50acceb339a277bf67425
      - PORT=80
      - ADMIN_PASSWORD=kettu
